from: netflix-eureka-server-2.0.0.RC1
server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 30               # 默认90秒没收到请求，剔除服务
    lease-renewal-interval-in-seconds: 10                   #心跳间隔默认30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true                                       # 注册当前实例
    register-with-eureka: true                                # 发现其他实例
    eureka-service-url-poll-interval-seconds: 60            # 对发现服务信息更新频率，默认5分钟，单位秒
  server:
    enable-self-preservation: false                           # 保护机制，测试时关闭保证服务及时更新
    eviction-interval-timer-in-ms: 30000                      # 清理服务间隔时间毫秒，默认0


