server:
  port: 8761
spring:
  application:
    name: scloud-eureka
eureka:
  client:
    service-url:
      defaultZone: http://192.168.200.110:39111/eureka/,http://192.168.200.111:39111/eureka/
    # 注册当前实例
    fetch-registry: true
    # 发现其他实例
    register-with-eureka: true
  server:
    # 保护机制，测试时关闭保证服务及时更新
    enable-self-preservation: false
