server:
  port: 8761
spring:
  application:
    name: scloud-eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${hostname:localhost}
  client:
    service-url:
      defaultZone: http://192.168.200.110:39111/eureka/,http://192.168.200.111:39111/eureka/
    # 注册当前实例
    fetch-registry: false
    # 发现其他实例
    register-with-eureka: false
    eureka-service-url-poll-interval-seconds: 60
  server:
    # 保护机制，测试时关闭保证服务及时更新
    enable-self-preservation: false
